2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_setup.py:_flush():81] Current SDK version is 0.22.1
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_setup.py:_flush():81] Configure stats pid to 2408299
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_setup.py:_flush():81] Loading settings from /home/sidcs/.config/wandb/settings
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_setup.py:_flush():81] Loading settings from /gpfs/accounts/profdj_root/profdj0/sidcs/codebase/speaker_embedding_codebase/wandb/settings
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_init.py:setup_run_log_directory():705] Logging user logs to ./wandb_logs/wandb/run-20251005_170901-p1xpsxs3/logs/debug.log
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to ./wandb_logs/wandb/run-20251005_170901-p1xpsxs3/logs/debug-internal.log
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_init.py:init():832] calling init triggers
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-10-05 17:09:01,615 INFO    MainThread:2408299 [wandb_init.py:init():880] starting backend
2025-10-05 17:09:03,324 INFO    MainThread:2408299 [wandb_init.py:init():883] sending inform_init request
2025-10-05 17:09:03,345 INFO    MainThread:2408299 [wandb_init.py:init():891] backend started and connected
2025-10-05 17:09:03,347 INFO    MainThread:2408299 [wandb_init.py:init():961] updated telemetry
2025-10-05 17:09:03,357 INFO    MainThread:2408299 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-05 17:09:03,873 INFO    MainThread:2408299 [wandb_init.py:init():1036] starting run threads in backend
2025-10-05 17:09:05,034 INFO    MainThread:2408299 [wandb_run.py:_console_start():2506] atexit reg
2025-10-05 17:09:05,034 INFO    MainThread:2408299 [wandb_run.py:_redirect():2354] redirect: wrap_raw
2025-10-05 17:09:05,035 INFO    MainThread:2408299 [wandb_run.py:_redirect():2423] Wrapping output streams.
2025-10-05 17:09:05,035 INFO    MainThread:2408299 [wandb_run.py:_redirect():2446] Redirects installed.
2025-10-05 17:09:05,113 INFO    MainThread:2408299 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-05 17:09:05,134 INFO    MainThread:2408299 [wandb_run.py:_config_callback():1392] config_cb None None {'num_class': 5796}
2025-10-05 17:15:13,690 INFO    wandb-AsyncioManager-main:2408299 [service_client.py:_forward_responses():80] Reached EOF.
2025-10-05 17:15:13,690 INFO    wandb-AsyncioManager-main:2408299 [mailbox.py:close():137] Closing mailbox, abandoning 1 handles.
2025-10-05 17:15:14,652 ERROR   MainThread:2408299 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2427, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 801, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
2025-10-05 17:15:14,728 ERROR   MainThread:2408299 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2427, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 801, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
2025-10-05 17:15:14,728 ERROR   MainThread:2408299 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2427, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 801, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/scratch/profdj_root/profdj0/sidcs/envs/miniconda3/envs/mtse/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
